spring:
  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      force: true

server:
  address: 127.0.0.1
  port: 6666
  context-path: /
  tomcat:
    max-threads: 800
    uri-encoding: utf-8